### ISSUE TITLE
List of small enhancements/fixes

### ISSUE THREAD

**Issue by Lurkars** [Lurkars/gloomhavensecretariat#160]
Issue for collecting small enhancements.

- [x] fix absent keyboard shortcut [v0.79.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.79.4)
- [x] move Ally/Allied toggle to stats dialog to avoid accidentally triggering switch [v0.78.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.78.2)
- [x] setting to apply shield value on damage [v0.76.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.76.0) (solved as applicable condition, disabled by default)
- [x] settings to enable/disable applying of conditions for every single condition [v0.76.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.76.0)
- [x] fix item buy bug on item shop [v0.75.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.75.5)
- [x] improve performance of scenario lists [v0.75.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.75.5)
- [x] add item count to shop for sold/retired items
- [x] add sold items to shop if not available before
- [x] mark new standees when opening room [v0.72.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.72.2)
- [x] fix battle goal warning for absent characters [v0.71.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.71.5)
- [x] fix owned items in search [v0.71.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.71.5)
- [x] add solo rewards [v0.71.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.71.5)
- [x] multi standee menu for summons [v0.70.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.70.4)
- [x] fix z-index hp vs. Conditions  [v0.69.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.69.0)
- [x] fix end turn when last standee killed
- [x] order of characters on scenario summary
- [x] fix fist solo section 1 room
- [x] check FH scenario 122 rewards
- [x] make different character form titles also available on level menu
- [x] add FH style for prosperity bar [v0.66.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.66.3)
- [x] fix summons turn applying long rest  [v0.66.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.66.3)
- [x] add custom tokens for characters [v0.66.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.66.0)
- [x] change standee number (allow used number and replace other written '?') [v0.65.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.65.7)
- [x] add menu to apply certain actions to all characters at once (like damage, gain/loose X gold etc) [v0.62.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.62.2) as `Event Effects` menu
- [x] fix missing scenario reward: choose scenario (for example GH  Scenario 13!)  [v0.60.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.60.6)
- [x] add/fix keyboard shortcuts as described in #90 [v0.61.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.61.0)
- [x] apply and persist random item loot card: draw item, mark as drawn for future sessions  [v0.59.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.3)
- [x] option to add edition on character menu while in edition campaign for crossover characters [v0.59.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.0)
- [x] element action on ability cards also for wild element (#157) [v0.57.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.57.7)
- [x] add shortcut for toggling active figures [v0.57.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.57.7)
- [x] buttons to show/hide attack modifier deck [v0.56.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.56.0)
- [x] hide editions without results in character filtering [v0.55.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.55.0)
- [x] fix wrong standee numbers for special bosses using monster standees (like "shared" standee count etc) [v0.53.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.53.0)
- [x] consider STUN condition on ability actions and shield indicator [v0.50.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.50.2)
- [x] apply treasure rewards [v0.49.12](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.12)
- [x] no undo event for initiative if not changed [v0.49.12](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.12)
- [x] add indicator for hand size [v0.49.12](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.12)
- [x]  change summon state after next round instead of draw [v0.49.12](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.12)
- [x] fix special target stats for living bones [v0.49.12](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.12)
- [x] check issue with summon action with multiple standees [v0.49.12](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.12)
- [x] setting for disable round/turn confirmation (#159)  [v0.49.10](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.10)
- [x] disable round/turn confirmation when all automatic turn actions are disabled (#159)  [v0.49.10](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.10)
- [x] checkbox to filter all completed scenarios in scenario list in campaign mode [v0.49.10](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.10)
- [x] add campaign mode toggle to **Set Edition** menu [v0.49.10](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.10)
- [x] fix scenario summary for FH casual mode: don't show not gained bonuses [v0.49.10](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.10)
- [x] add info for casual mode on scenario summary [v0.49.10](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.10)
- [x] fix TAB-key shortcut for initiative with absent characters [v0.49.10](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.10)

**Comment by OZ10** [comment]
Just finished scenario 38 and was given 1 inspiration (correct) and then a bonus 2 inspiration (I couldn't see why) after successful completion. Possible bug.

**Comment by Lurkars** [comment]
See rule book page 48, point 7.

On scenario completion, you gain 4-player count inspiration. So I think you had a 2 player party? Then you gain 2 bonus inspiration for every completed scenario.

**Comment by OZ10** [comment]
Didn't notice that the app was doing this after each scenario. Is that new?

**Comment by Lurkars** [comment]
Yes, came a few releases ago in #268

**Comment by OZ10** [comment]
Ah. My fault then. Ignore me!

**Comment by datenshi888** [comment]
The prosperity tracker in app uses different darker squares than the sheet one (I believe the sheet darkens every 5th prosperity square and the app darkens every prosperity level increase square. Would it be possible to sync those?

**Comment by Lurkars** [comment]
> The prosperity tracker in app uses different darker squares than the sheet one (I believe the sheet darkens every 5th prosperity square and the app darkens every prosperity level increase square. Would it be possible to sync those?

Should be done in  [v0.66.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.66.3)

**Comment by Lurkars** [comment]
> Scenario 87 is force-linked with scenario 88. Currently only linked implemented.

Thanks, should be fixed in [v0.132.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.132.3).

**Comment by alibaba56734** [comment]
PQ 19 should gain blueprint upon selection. 

<img width="419" height="586" alt="Image" src="https://github.com/user-attachments/assets/66be2a0f-bbd4-4135-a514-113b71054c93" />

After this it is still upon the character to craft it, so maybe checkbox in character sheet should change to Owning item?

<img width="473" height="247" alt="Image" src="https://github.com/user-attachments/assets/0e427091-2443-4cf4-abd3-5e935318db23" />

**Comment by alibaba56734** [comment]
Effect from Buildings 5,12 and 17 should mentio n "... for 2 gold **each**".

<img width="1069" height="184" alt="Image" src="https://github.com/user-attachments/assets/ac746914-714f-45cc-8fdd-0399f5a29b18" />

<img width="910" height="464" alt="Image" src="https://github.com/user-attachments/assets/952f3664-7beb-4de0-bf83-81234f19b8f0" />

**Comment by Lurkars** [comment]
Thanks, label should be fixed in [v0.136.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.136.2).

**Comment by alibaba56734** [comment]
Invisible icon missing in item 37

<img width="272" height="397" alt="Image" src="https://github.com/user-attachments/assets/2748f677-1f3a-4509-ad81-425634f39b3a" />

**Comment by Over-Wright** [comment]
Would be nice for the scenario flow chart view for solo scenarios to have character icons instead of arbitrary numbers that are artifacts of how the data is organized. Otherwise there's no way to know which one is which character. The set scenario menu does it right, so can probably just copy that.

Examples from a GH2E campaign.

Confusing:
<img width="333" height="67" alt="Image" src="https://github.com/user-attachments/assets/7cba47d4-03b3-4e8f-bc82-356978013983" />

Clear:
<img width="600" height="127" alt="Image" src="https://github.com/user-attachments/assets/5df0e5ef-0a1c-4514-bf6f-af092ec5ac89" />

Those meaningless numbers also appear in the scenario chart pop up and while playing the scenario, but there they aren't a big deal. At that point you should know which character's scenario it is.

**Comment by Over-Wright** [comment]
> Sadly, I am just using an external library for the chart and only text is visible. Anyways, I think the chart is pretty useless for solo scenarios, so hopefully no big issue.

Makes sense. If it helps, the reason I use it is for planning - the scenario pop-up that lets you see the monsters (and click on them to see stats and ability cards) is incredibly helpful. I didn't find a way to access that info outside of the chart view (well, without just starting the scenario).

**Comment by alibaba56734** [comment]
I noticed in the latest update, the text in the lower bar is slightly off-center. Not sure if this is intentional, just wanted to let you know. Running on Chrome/Windows 11.

<img width="1908" height="1009" alt="Image" src="https://github.com/user-attachments/assets/4913510d-a4ac-4a69-9215-c149f0be415e" />

**Comment by alibaba56734** [comment]
Also, Event deck overview now opens in left side of the screen, whereas it used  to open in center. 
When ticking resolved cards, no extra column is being shown:

<img width="1906" height="1071" alt="Image" src="https://github.com/user-attachments/assets/ad496ce5-fb73-4723-96ac-811d3e996908" />

**Comment by Lurkars** [comment]
> I noticed in the latest update, the text in the lower bar is slightly off-center. Not sure if this is intentional, just wanted to let you know. Running on Chrome/Windows 11.

I can't see difference to older versions. so please specifiy what you mean with "off-center". You can compare with older version through history like: https://v0-130-0.gloomhaven-secretariat.de

> Also, Event deck overview now opens in left side of the screen, whereas it used to open in center. When ticking resolved cards, no extra column is being shown:

Please send me you game state for this. Cannot reproduce, but I know that pop-up position only breaks on real errors, so it must be a bug.

**Comment by alibaba56734** [comment]
> > I noticed in the latest update, the text in the lower bar is slightly off-center. Not sure if this is intentional, just wanted to let you know. Running on Chrome/Windows 11.
> 
> I can't see difference to older versions. so please specifiy what you mean with "off-center". You can compare with older version through history like: https://v0-130-0.gloomhaven-secretariat.de
> 

The block in the lower bar with Events and numbers is not centered in the bar. Maybe this was already the case, or maybe it is intentional. Just wanted to let you know.

I have sent you the game state by mail.

**Comment by battis124** [comment]
> > ```
> > 7. now both modals will show up again and if you close them, the shortcuts wont work, for example: fullscreen - `f`, AM draws - `m,d,a`, Navigating over figures -`Tab`
> > ```
> 
> I actually see an issue here, that the confirm initiative dialog is shown again, anyways all hotkeys are still working fine for me here.

I was able to reproduce the issue again, and I believe I may have identified the source of the problem - the fullscreen setting. Please check the video (ignore the colors, the compression tool altered them slightly).

https://streamable.com/8fkozm


Unfortunately, my recording only captures keyboard press outside fullscreen mode, so here’s what I did while in fullscreen:
- At 0:18, the app automatically enters fullscreen mode because I have that option enabled in settings.
- Between 0:35 and 0:41, the only keys I press are `Tab` + `1`,`2`, `3`, + mouse click(visible on video).

At 1:06, after I disable fullscreen mode, the settings modal appears - you can see the background opacity change and the standee modal shows up. After that, everything works normally.

It appears that entering fullscreen at a specific moment may prevent some modals from rendering correctly, which then blocks keyboard shortcuts.

**Comment by Lurkars** [comment]
Was able to reproduce somehow, hopefully fixed now in [v0.147.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.147.2).

For the other issues:
>  When there is only one card in AM deck, draw with advantage/disadvantage does not work

This is currently technically complicated, because on shuffle I am currently losing information about last card. So this will take a while

> If the time passes in FH calendar, add small modal to display section(s) to read if there is any marked. No need to automate all sections, just show information like "Week X: read 183.3"

This is a cool idea, just didn't had time for this now.

> in scenario 65 FH, section 89.1 change special object to not be able to assign any status effects:

Not sure about this one, the section book says it's an ally, not objective 🤷 

>  Also in scenario 65 there is special rule to add + 1 push to all enemy attacks, I think it should sum up to push 2, instead of push 1, push 1 if monster have its own push ability:

Also need more time for this one

**Comment by battis124** [comment]
> This is currently technically complicated, because on shuffle I am currently losing information about last card. So this will take a while

If it is not a easy fix than forget it, it’s not something that makes the app unusable.

> Not sure about this one, the section book says it's an ally, not objective 🤷

In the map setup, the core is marked with an orange border and an exclamation mark, so it is treated as an objective. The ally designation is there so players cannot attack it, but they can heal it.

a few new things 😛 :

- [ ] FH snowflake character perk 9 automation; If in the scenario some of the enemies are counted as ally, they should not get muddle status. The app should change monster to ally and then check perk 9 conditions. You can test this in FH scenario 18

I’ve added a large number of translations for FH items and noticed that some of the descriptions need correction:

- [ ] typo "yur" https://github.com/Lurkars/gloomhavensecretariat/blob/fbb78233ce396c30d4d0c2c513cee5a16b93b38b/data/fh/label/spoiler/en.json#L1208

- [ ] `%game.action.pierce%` -> %game.action.pierce:1%
https://github.com/Lurkars/gloomhavensecretariat/blob/fbb78233ce396c30d4d0c2c513cee5a16b93b38b/data/fh/label/spoiler/en.json#L1237
https://github.com/Lurkars/gloomhavensecretariat/blob/fbb78233ce396c30d4d0c2c513cee5a16b93b38b/data/fh/label/spoiler/en.json#L921
https://github.com/Lurkars/gloomhavensecretariat/blob/fbb78233ce396c30d4d0c2c513cee5a16b93b38b/data/fh/label/spoiler/en.json#L860

- [ ] `%game.action.pierce%` -> %game.action.pierce:2%
https://github.com/Lurkars/gloomhavensecretariat/blob/fbb78233ce396c30d4d0c2c513cee5a16b93b38b/data/fh/label/spoiler/en.json#L897

- [ ] `%game.action.pierce%` -> %game.action.pierce:3%
https://github.com/Lurkars/gloomhavensecretariat/blob/fbb78233ce396c30d4d0c2c513cee5a16b93b38b/data/fh/label/spoiler/en.json#L594
https://github.com/Lurkars/gloomhavensecretariat/blob/fbb78233ce396c30d4d0c2c513cee5a16b93b38b/data/fh/label/spoiler/en.json#L921


- [ ] \`hide\` -> `%game.resource.hide%`
https://github.com/Lurkars/gloomhavensecretariat/blob/fbb78233ce396c30d4d0c2c513cee5a16b93b38b/data/fh/label/spoiler/en.json#L1030

- [ ] `%game.action.shield%` -> `%game.action.shield:1%`
https://github.com/Lurkars/gloomhavensecretariat/blob/fbb78233ce396c30d4d0c2c513cee5a16b93b38b/data/fh/label/spoiler/en.json#L1022

- [ ] missing `or` between status
https://github.com/Lurkars/gloomhavensecretariat/blob/fbb78233ce396c30d4d0c2c513cee5a16b93b38b/data/fh/label/spoiler/en.json#L1452
https://github.com/Lurkars/gloomhavensecretariat/blob/fbb78233ce396c30d4d0c2c513cee5a16b93b38b/data/fh/label/spoiler/en.json#L454
https://github.com/Lurkars/gloomhavensecretariat/blob/fbb78233ce396c30d4d0c2c513cee5a16b93b38b/data/fh/label/spoiler/en.json#L1261

- [ ] missed label for translation:
https://github.com/Lurkars/gloomhavensecretariat/blob/fbb78233ce396c30d4d0c2c513cee5a16b93b38b/data/fh/items.json#L1791
https://github.com/Lurkars/gloomhavensecretariat/blob/fbb78233ce396c30d4d0c2c513cee5a16b93b38b/data/fh/items.json#L4035
https://github.com/Lurkars/gloomhavensecretariat/blob/fbb78233ce396c30d4d0c2c513cee5a16b93b38b/data/fh/items.json#L4507

**Comment by keinkurt** [comment]
Hey Lurkers, their is a small issue. The hand size of Triangles is wrong. He is a 10 cards class, but in the app it shows 12 cards.

<img width="705" height="456" alt="Image" src="https://github.com/user-attachments/assets/cf31d32c-dfc1-49b1-8a14-fcb2b62cacca" />

**Comment by brentrichardjr** [comment]
Scrolling resolved events column (road or city) behaves different than "in deck" or "locked" columns. Scroll only works if touch based scrolling is attempted on "resolved" title of column. Attempting anywhere else in the column picks up the card under the tap. This apps for the cards to be rearranged and also allows can the column to scroll horizontally if card is moved to left or right edge.

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/49874828-d977-4e0c-b80b-87e19046e820" />

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/a24cb813-f1e0-4b21-b05e-7c1d34985ae1" />

I may be doing something wrong, but event cards are not discarded after being resolved. Discovered after multiple repeats appeared. Have since started manually discarding when applicable.

**Comment by Lurkars** [comment]
> Scrolling resolved events column (road or city) behaves different than "in deck" or "locked" columns. Scroll only works if touch based scrolling is attempted on "resolved" title of column. Attempting anywhere else in the column picks up the card under the tap. This apps for the cards to be rearranged and also allows can the column to scroll horizontally if card is moved to left or right edge.

> I may be doing something wrong, but event cards are not discarded after being resolved. Discovered after multiple repeats appeared. Have since started manually discarding when applicable.

The Screenshots looks like a lot things messed up. Please create a separate issue for this. Doesn't look like just a small fix and I need a lot more information like Browser, Version, OS etc. Maybe Export of Game and Settings! Thank you.

**Comment by brentrichardjr** [comment]
Default zoom (select "Reset Zoom") level with "Portrait-mode Optimization" hides far left icons on character menu popup.

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/09e8bac5-f579-4b33-b552-a051449fd54b" />

Menu works as expected at default zoom in landscape orientation.

<img width="2340" height="1080" alt="Image" src="https://github.com/user-attachments/assets/36932a8f-8925-4a63-8e60-8c8508674729" />


Icons visible in portrait orientation once pressing "Zoom out" three times.

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/ffd896ca-105a-4992-aad7-39f368b34c03" />

**Comment by Lurkars** [comment]
> Default zoom (select "Reset Zoom") level with "Portrait-mode Optimization" hides far left icons on character menu popup.

Should be fixed in [v0.158.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.158.1). Happy if you can also check again.

**Comment by brentrichardjr** [comment]
> Should be fixed in [v0.158.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.158.1). Happy if you can also check again.

Indeed, it is. You're the best. Thanks

**Comment by brentrichardjr** [comment]
Found a couple of typos in the setting menu. 

"Automatic Theme"

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/876299c6-c54a-4320-9eae-62bfec247ff8" />

"Character"

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/1c12eb71-b895-44e5-ab24-81016eded36a" />

**Comment by Lurkars** [comment]
Should be fixed in [v0.162.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.162.0)

**Comment by Over-Wright** [comment]
Plague (and I guess Chill as the other stacking condition) changes via the entities menu should not set everything to a specific value but instead be additive. Right now it's impossible to bulk add plague to figures that have different plague values. It would be better to add to (or subtract from) the existing value for each figure selected.

Possibly the UI should then change to have +/- buttons like for other additive numerical changes in the entities menu (health, shield, retaliate, etc).

**Comment by brentrichardjr** [comment]
GH2E. Scenario 70. Room 3 (80.2). 4 player game has 2 Elite and 3 Normal Rending Drakes. Currently, opening door auto adds 2 Elites and 2 Normals.

**Comment by brentrichardjr** [comment]
Zoomed text on item cards using Android app. Not present in browser or pwa.

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/a905e47a-417b-4fa0-9558-bc4a6955a0ed" />

**Comment by Lurkars** [comment]
> Plague (and I guess Chill as the other stacking condition) changes via the entities menu should not set everything to a specific value but instead be additive. Right now it's impossible to bulk add plague to figures that have different plague values. It would be better to add to (or subtract from) the existing value for each figure selected.
> 
> Possibly the UI should then change to have +/- buttons like for other additive numerical changes in the entities menu (health, shield, retaliate, etc).

I changed the value to be relative now in [v0.163.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.163.0). I hope this works properly and I didn't break anything else.

> GH2E. Scenario 70. Room 3 (80.2). 4 player game has 2 Elite and 3 Normal Rending Drakes. Currently, opening door auto adds 2 Elites and 2 Normals.

The whole sections seemed to have not correct monsters, should also be fixed in [v0.163.0]https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.163.0) now!

> Zoomed text on item cards using Android app. Not present in browser or pwa.

I cannot reproduce, can you provide a settings export for me, so I can check if this is related to something special?

**Comment by Over-Wright** [comment]
> > Plague (and I guess Chill as the other stacking condition) changes via the entities menu should not set everything to a specific value but instead be additive. Right now it's impossible to bulk add plague to figures that have different plague values. It would be better to add to (or subtract from) the existing value for each figure selected.
> > Possibly the UI should then change to have +/- buttons like for other additive numerical changes in the entities menu (health, shield, retaliate, etc).
> 
> I changed the value to be relative now in [v0.163.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.163.0). I hope this works properly and I didn't break anything else.

Looks like it works to me, great job!

One thing, though, is it seems like you included what the code labels as "upgrade" conditions (Wound/Poison X) with this. My read of the Crimson Scales rulebook is that those should still use the old "set" behavior instead of the new relative behavior. But I've never played content that uses these conditions so I'm not sure.

**Comment by brentrichardjr** [comment]
> I cannot reproduce, can you provide a settings export for me, so I can check if this is related to something special?

The android apk data management exports don't appear to do anything. I reset all settings and only enabled "Character Items". Unable to reproduce in browser or pwa.

Maybe device specific? Samsung Galaxy S23 (SM-S991U)

**Comment by Lurkars** [comment]
> > I cannot reproduce, can you provide a settings export for me, so I can check if this is related to something special?
> 
> The android apk data management exports don't appear to do anything. I reset all settings and only enabled "Character Items". Unable to reproduce in browser or pwa.
> 
> Maybe device specific? Samsung Galaxy S23 (SM-S991U)

Can you checkout [v0.164.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.164.0). I hope the issue is fixed there.

**Comment by brentrichardjr** [comment]
> Can you checkout [v0.164.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.164.0). I hope the issue is fixed there.

Fixed.

**Comment by brentrichardjr** [comment]
GH2E. Scenario 16. Room 1 (30.2). 4 player game has 1 Elite and 2 Normal Bandit Archers. Currently, opening door auto adds 1 Elite and 1 Normal.

**Comment by Lurkars** [comment]
> GH2E. Scenario 16. Room 1 (30.2). 4 player game has 1 Elite and 2 Normal Bandit Archers. Currently, opening door auto adds 1 Elite and 1 Normal.

Thanks, should be fixed in [v0.165.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.165.1)

**Comment by Over-Wright** [comment]
Repeating a previously completed scenario in Frosthaven and GH2E is supposed to work like casual mode in GH1 - award XP, loot, and treasure, but not rewards from the scenario conclusion. You can _almost_ get this behavior by turning off campaign mode and then clicking "gain rewards anyway," but you miss some game specific rewards you're supposed to get on a repeat but not casual mode (like challenge and imbuement progress).

May not actually be worth fixing, since I doubt many people repeat scenarios. Just mentioning it in case the fix is super easy.

**Comment by Lurkars** [comment]
> Repeating a previously completed scenario in Frosthaven and GH2E is supposed to work like casual mode in GH1 - award XP, loot, and treasure, but not rewards from the scenario conclusion. You can _almost_ get this behavior by turning off campaign mode and then clicking "gain rewards anyway," but you miss some game specific rewards you're supposed to get on a repeat but not casual mode (like challenge and imbuement progress).
> 
> May not actually be worth fixing, since I doubt many people repeat scenarios. Just mentioning it in case the fix is super easy.

Hopefully fixed this in [v0.167.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.167.0).
