### ISSUE TITLE
More modular tracking

### ISSUE THREAD

**Issue by mentonin** [Lurkars/gloomhavensecretariat#381]
### Is your feature request related to a problem? Please describe.

This program can track an amazing amount of things, but it may be too much for some people. In particular, things that use up space ma be annoying if not being used, especially in small screens

### Describe the solution you'd like

An option to hide some things to save screen space be hidden for people that don't use them.

Examples that I thought of:

- [ ] Most things related to character, such as HP, loot, XP. An option for characters to be just a thin line would save vertical space, and still allow initiative tracking, for people that want the app just for AI help.
- [ ] Hide characters. Equivalent to having no characters during the scenario, but with the advantage of auto scenario level and persistent character tracking. For people who want to track even their own initiative, but want to save and automate the campaign.
- [X] Hide monster standees. For people who want to track monsters near the monsters. This exists already!
- [X] Monster and Allies Attack Modifier Deck. For people who like drawing those attack odds. This exists already! (only for allies)
- [X] Loot Deck. For people who like the physical loot rush. This exists already!
- [ ] Character/Monster art. For people with very narrow screens?
- [ ] Inline exp/loot display. Also for narrow screens?
- [ ] Base monster stats. For the narrowest screens and the brave.

Most of those could be moved into submenus when deactivated, so people could choose between convenience or screen real state. There are probably other options that could be added, those are just some ideas.

I understand that implementing all of this may be too much work for too little benefit, but some items should be feasible.

### Describe alternatives you've considered

Scrolling a lot

**Comment by Lurkars** [comment]
Small notice: Hide Characters is useless. If you don't want to track characters, don't add them and check `Manual character count` in Level Menu for automatic standee rules. Of course Level must be then set manually, but for such edge case I think this is fine.

**Comment by mentonin** [comment]
As I said, the advantage of hiding characters (instead of not adding them) would be the characters sheets and auto level

**Comment by Lurkars** [comment]
If you don't want to use the app for its main purpose to assist playing scenarios,I would recommend using a campaign tracker app instead. 😅 The character sheets are there for two reasons: for myself, because I don't like to track on paper and most importantly to support character AM decks which requires setup perks.

**Comment by mentonin** [comment]
I mean you can use the app to assist only with monsters during the scenario and use all its campaign tracking features. The way my group plays it, we track everything for monsters on the scenario, and everything for characters physically, except for initiative (that is why I asked for the "thin character" option)

**Comment by Lurkars** [comment]
Regarding

>  Hide characters. Equivalent to having no characters during the scenario, but with the advantage of auto scenario level and persistent character tracking. For people who want to track even their own initiative, but want to save and automate the campaign.

There is already a setting to not require initiative, at least the characters then only take up space. Combined with a visual setting for more compact characters, I think really hide characters (only during a scenario) is to niche for me to consider. A more compact style is definitely sth. I am considering.

**Comment by Lurkars** [comment]
Added a `compact` character board on [v0.77.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.77.2). It's a setting under `Theme`. Happy about feedback.

**Comment by Lurkars** [comment]
Addressed some points in #442
